name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with: 
          node-version: 12.x
          
      - name: Install Dependencies
        run: yarn
        
      - name: Build Project
        run: yarn build
      
      - name: Running Tests
        run: yarn build --ci
